runtime: nodejs
env: flex

manual_scaling:
  instances: 1

env_variables:
  PORT: 3000  # Replace with your preferred port

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cpu_utilization:
    target_utilization: 0.65
